### ISSUE TITLE
Question about cif

### ISSUE THREAD

**Issue by Mddct** [MingLunHan/CIF-PyTorch#1]
Only the boundary information in cif, but whether the silence or noise in the front will cause the accumulation of the first pronunciation to be particularly large

**Comment by MingLunHan** [comment]
Hello! welcome!

First, let's talk about the situation where there is no noise. We checked the weight of each frame and drawn a picture, the slience frames almost make no contribution to the accumulation. The weight of slience frames are almost very small value. This is our observation. You can also try to reproduce it with codes in this repo.

Then, let's talk about the noisy situation.  In fact, the noise in speech will influence the generation of weight of its corresponding frames. If the model is not designed properly or the training strategy is not appropriate, the model cannot adapt the noisy data. If you conduct speech recognition with a model that cannot well adapt noisy environment, the phenomenon you mentioned above may occur. 

Finally, I think what you mentioned is possible, but you can try to add some augmented noisy data to enhance the training of your model. Just like how you solve the noise problem of other ASR models. Of course, this is the most simple and straightforward approach. You can also do some tests and solve this problem with more powerful techiniques.

Thanks for your question!

**Comment by Mddct** [comment]
thank you replay
