### ISSUE TITLE
ctc aligment loss?

### ISSUE THREAD

**Issue by Mddct** [MingLunHan/CIF-PyTorch#2]
Thers is a ctc aligment loss In "BOUNDARY AND CONTEXT AWARE TRAINING FOR CIF-BASED
NON-AUTOREGRESSIVE END-TO-END ASR"

How do you determine whether a ctc probs is a spike that exceeds the threshold using greedy search or a prefix beam search？

**Comment by MingLunHan** [comment]
First of all, thank you for your attention! I am not the author of the article you mentioned, but I did reproduce his method. His method is effective and useful. But I cannot understand your specific question at the moment. If you are still confused about this issue, could you provide more comprehensive background information?

**Comment by MingLunHan** [comment]
Hello, in my memory, the label sequence determined by CTC alignment does not seem to require searching, as it is determined by a threshold.
