### ISSUE TITLE
如何让训练cif_output的输出恰好等于target_length

### ISSUE THREAD

**Issue by xishuxishu** [MingLunHan/CIF-PyTorch#3]
非常感谢您提供的代码，但是我有一个小困惑，weight的sum等于target_length，为什么cif_output输出的长度与target_length不符，按照论文原理，应该恰好等于target_length，如果想要它刚好等于target_length，应该如何修改code呢

**Comment by MingLunHan** [comment]
在我印象中，这套代码可能确实会有这个问题，但是貌似是偶发现象，不影响整体的训练。之所以会存在CIF_OUTPUT输出长度和target_length不符合的地方，后来分析的时候，貌似是受到精度影响，最后一位有时可能会多发放或者少发放。你也可以借鉴其他CIF实现，都是可以的。或者你也可以直接使用这个repo，可以直接在aishell1上跑出来个不错的结果：https://github.com/MingLunHan/CIF-HieraDist 而且最后一位通常是 \<eos\> token，所以如果出现这种情况，就直接截断成ground truth & cif_outputs 的两者里面较短的一个就可以了。

**Comment by MingLunHan** [comment]
> 非常感谢您提供的代码，但是我有一个小困惑，weight的sum等于target_length，为什么cif_output输出的长度与target_length不符，按照论文原理，应该恰好等于target_length，如果想要它刚好等于target_length，应该如何修改code呢

Hello, if there are no further questions, I will temporarily close this issue.
